const StoriesList = [
  { author: 'Adam', category: 'adult life', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla odio dui, ultrices eget dapibus sed, bibendum congue diam. Nulla ac massa a nibh vulputate consectetur vitae nec purus. Donec mollis, erat vel fringilla mollis, ex ex fringilla quam, vel elementum ipsum risus in arcu. Maecenas ornare magna id ante pharetra, quis tempus ligula lobortis. Aliquam tellus mauris, semper id semper eu, iaculis eu velit. Donec tincidunt blandit elit, in feugiat est ornare a. Sed euismod dignissim mauris eget pulvinar. Donec vehicula maximus posuere. Morbi a consequat metus. Aenean efficitur, risus at rutrum tincidunt, diam lacus suscipit turpis, nec consequat mauris dui a ipsum.' },
  { author: 'Zaq', category: 'scary', content: 'Etiam congue velit pharetra nisl accumsan, non venenatis dui elementum. Nulla facilisi. Mauris dictum elit lorem, sed rutrum nisi varius at. Aenean nec lorem lacus. Vestibulum ultrices luctus neque, id pretium quam ornare vitae. Aenean luctus neque at nibh tristique congue. Pellentesque ac justo auctor, mattis lacus in, euismod massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut euismod suscipit nisi, sed ullamcorper eros placerat at. Sed et augue viverra erat volutpat dictum eu eu dolor. Curabitur ultricies lorem eu sem semper, id consequat enim blandit. Maecenas vehicula a sapien porttitor sollicitudin. Sed congue tempor nisi non maximus.' },
  { author: 'Adam', category: 'scary', content: 'Nulla fermentum dui mauris, vitae ultricies odio pulvinar id. Sed nec ultrices nisl. Proin quam augue, mollis sed eros ornare, pellentesque fermentum nulla. Vivamus rhoncus porta nunc, eget accumsan sapien rutrum nec. Donec blandit iaculis nisi egestas iaculis. In lacus augue, ultricies vitae pretium ut, placerat ut risus. Pellentesque ex est, pharetra sit amet turpis suscipit, sollicitudin tincidunt risus. Sed nec orci mattis, blandit lectus sed, ornare elit. Nunc sapien justo, posuere non rhoncus non, elementum eget nunc. Suspendisse elementum orci non justo porta, at placerat risus feugiat. In suscipit eu dui ac vestibulum.' },
  { author: 'Zaq', category: 'adult life', content: 'Fusce sed lorem eu ante tincidunt ultrices et vel orci. Sed et turpis vitae magna suscipit vulputate. Nullam tincidunt neque in lorem semper vulputate. Proin turpis lorem, tincidunt ac iaculis non, interdum sit amet dolor. Cras convallis ultrices est, eget blandit est commodo et. Pellentesque a metus non felis dignissim volutpat ut dignissim odio. Aenean eget iaculis quam, ut imperdiet orci. Integer ac volutpat justo. Praesent et risus fermentum, facilisis mauris quis, pretium felis. Nunc lorem ante, rutrum sit amet lacus nec, lobortis egestas lorem. Sed cursus purus nisi, ac aliquet dui sodales in. Nam tincidunt nibh ex, non dignissim tortor sagittis at. Aenean eget lacus nec odio porta pellentesque.' },
  { author: 'Adam', category: 'adult life', content: 'Nam laoreet, augue et euismod imperdiet, tortor massa tincidunt ligula, ut congue dolor turpis vitae est. Nulla facilisi. Nulla ultrices ex leo, nec vulputate eros vestibulum in. Curabitur aliquam eros eu orci mollis, et molestie mauris laoreet. Aenean in nulla id nibh interdum faucibus. Curabitur ornare dolor elit, sit amet ullamcorper tortor commodo nec. Maecenas consequat, felis ut vehicula dapibus, libero dolor convallis leo, et molestie quam purus sed erat. Suspendisse malesuada et ante a sodales. Ut metus mauris, egestas ac volutpat a, tristique vitae enim. Mauris dapibus fermentum urna sed viverra.' }
];

export default StoriesList;
